CREATE DATABASE DB_CURSO_DA_MINHA_VIDA;

USE DB_CURSO_DA_MINHA_VIDA;

CREATE TABLE TB_CATEGORIAS (
ID BIGINT AUTO_INCREMENT,
AREA VARCHAR (255) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_CURSOS(
CODIGO BIGINT AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
MODALIDADE VARCHAR (255),
PRECO FLOAT (6,2),
CATEGORIA_ID BIGINT,
PRIMARY KEY (CODIGO),
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIAS (ID)
);

INSERT INTO TB_CATEGORIAS (AREA)
VALUES ("LÍNGUAS");
INSERT INTO TB_CATEGORIAS (AREA)
VALUES ("HABILIDADES MANUAIS");
INSERT INTO TB_CATEGORIAS (AREA)
VALUES ("EXATAS");
INSERT INTO TB_CATEGORIAS (AREA)
VALUES ("HUMANAS");
INSERT INTO TB_CATEGORIAS (AREA)
VALUES ("TECNOLOGIA");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("INGLÊS NA PRÁTICA", "ONLINE", 650 , 1);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("ESPANHOL COM MÚSICA", "HÍBRIDO", 550 , 1);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("CROCHÊ PARA INICIANTES", "PRESENCIAL", 700 , 2);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("COSTURE COMO A SUA VÓ", "ONLINE", 500 , 2);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("RELEMBRANDO A MATEMÁTICA", "HÍBRIDO", 990 , 3);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("VOCÊ CONHECE A NOSSA HISTÓRIA?", "ONLINE", 850 , 4);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("PROGRAME APPS PARA ANDROID", "ONLINE", 1000 , 5);
INSERT INTO TB_CURSOS (NOME, MODALIDADE, PRECO, CATEGORIA_ID)
VALUES ("PROGRAME APPS PARA IOS", "ONLINE", 1000 , 5);

SELECT * FROM TB_CURSOS;

SELECT * FROM TB_CURSOS WHERE PRECO > 500;
SELECT * FROM TB_CURSOS WHERE PRECO >= 600 AND PRECO <= 1000;
SELECT * FROM TB_CURSOS WHERE NOME LIKE "%J%";
SELECT * FROM TB_CURSOS INNER JOIN TB_CATEGORIAS ON TB_CURSOS.CATEGORIA_ID = TB_CATEGORIAS.ID;
SELECT * FROM TB_CURSOS INNER JOIN TB_CATEGORIAS ON TB_CURSOS.CATEGORIA_ID = TB_CATEGORIAS.ID WHERE ID = 3;
