CREATE DATABASE DB_SERVICO_RH; -- CRIA O BANCO DE DADOS

USE DB_SERVICO_RH; -- INFORMA QUAL BANCO DE DADOS SERÁ UTILIZADO PARA A CRIAÇA DE TABELAS

CREATE TABLE TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT, -- DEPENDENDO DO TAMANHO DA APLICAÇÃO, É BOM JÁ CRIAR GRANDE PARA ADICIONAR VÁRIAS COISAS
NOME VARCHAR(1000),
IDADE INT,
FUNCAO CHAR(255),
PRIMARY KEY(ID) -- ID É SEMPRE IDENTIFICADOR ÚNICO, NÃO SE REPETE, MESMO QUE SEJA APAGADO
);

INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO) 
VALUES ("ISABELLA", 20, "DEVA");
INSERT INTO TB_FUNCIONARIOS (NOME, IDADE, FUNCAO) 
VALUES ("NAYARA", 30, "DEVA"); -- ALTERAR TAMBÉM INSERE, NÃO PRECISA COPIAR A FUNÇÃO DESSA FORMA

SELECT * FROM TB_FUNCIONARIOS;