CREATE DATABASE DB_GENSCHOOL;

USE DB_GENSCHOOL;

CREATE TABLE TB_ALUNOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (1000),
SERIE INT,
TURMA CHAR(255),
TURNO CHAR(255),
MEDIA FLOAT,
PRIMARY KEY (ID)
);

INSERT INTO TB_ALUNOS (NOME, SERIE, TURMA, TURNO, MEDIA)
VALUES("THAIS", 9, "A", "MATUTINO", 8.5);
INSERT INTO TB_ALUNOS (NOME, SERIE, TURMA, TURNO, MEDIA)
VALUES("TIAGO", 5, "B", "VESPERTINO", 4.5);
INSERT INTO TB_ALUNOS (NOME, SERIE, TURMA, TURNO, MEDIA)
VALUES("LETICIA", 10, "D", "NOTURNO", 6.3);
INSERT INTO TB_ALUNOS (NOME, SERIE, TURMA, TURNO, MEDIA)
VALUES("LUCAS", 3, "C", "MATUTINO", 8.9);
INSERT INTO TB_ALUNOS (NOME, SERIE, TURMA, TURNO, MEDIA)
VALUES("NADIA", 8, "A", "VESPERTINO", 7.2);
INSERT INTO TB_ALUNOS (NOME, SERIE, TURMA, TURNO, MEDIA)
VALUES("NATAN", 6, "C", "MATUTINO", 9.6);
INSERT INTO TB_ALUNOS (NOME, SERIE, TURMA, TURNO, MEDIA)
VALUES("ANA", 12, "B", "MATUTINO", 5.9);
INSERT INTO TB_ALUNOS (NOME, SERIE, TURMA, TURNO, MEDIA)
VALUES("ANTONIO", 1, "A", "VESPERTINO", 9.9);

SELECT * FROM TB_ALUNOS;
SELECT * FROM TB_ALUNOS WHERE MEDIA > 7;
SELECT * FROM TB_ALUNOS WHERE MEDIA < 7;

ALTER TABLE TB_ALUNOS MODIFY MEDIA FLOAT(4,2);
UPDATE TB_ALUNOS SET MEDIA = 8.5 WHERE ID = 1;
UPDATE TB_ALUNOS SET MEDIA = 4.5 WHERE ID = 2;
UPDATE TB_ALUNOS SET MEDIA = 6.3 WHERE ID = 3;
UPDATE TB_ALUNOS SET MEDIA = 8.9 WHERE ID = 4;
UPDATE TB_ALUNOS SET MEDIA = 7.2 WHERE ID = 5;
UPDATE TB_ALUNOS SET MEDIA = 9.6 WHERE ID = 6;
UPDATE TB_ALUNOS SET MEDIA = 5.9 WHERE ID = 7;
UPDATE TB_ALUNOS SET MEDIA = 9.9 WHERE ID = 8;
