CREATE DATABASE DB_SERVICOS_RH;

USE DB_SERVICOS_RH;

CREATE TABLE TB_EMPREGADOS(
REGISTRO BIGINT AUTO_INCREMENT,
NOME VARCHAR (1000),
IDADE INT,
AREA CHAR (255),
CARGO CHAR (255),
SALARIO INT,
PRIMARY KEY(REGISTRO)
);

INSERT INTO TB_EMPREGADOS (NOME, IDADE, AREA, CARGO, SALARIO)
VALUES("ANA", 25, "JURÍDICO", "ADVOGADA JÚNIOR", 2500);
INSERT INTO TB_EMPREGADOS (NOME, IDADE, AREA, CARGO, SALARIO)
VALUES("JOÃO", 40, "TI", "DESENVOLVEDOR SÊNIOR", 15000);
INSERT INTO TB_EMPREGADOS (NOME, IDADE, AREA, CARGO, SALARIO)
VALUES("MARIA", 30, "COMPLIANCE", "ANALISTA PLENA", 7000);
INSERT INTO TB_EMPREGADOS (NOME, IDADE, AREA, CARGO, SALARIO)
VALUES("THOMAS", 20, "AUDITORIA", "ESTAGIÁRIO", 1500);
INSERT INTO TB_EMPREGADOS (NOME, IDADE, AREA, CARGO, SALARIO)
VALUES("JOANA", 18, "FINANCEIRO", "MENOR APRENDIZ", 1200);

SELECT * FROM TB_EMPREGADOS;
SELECT * FROM TB_EMPREGADOS WHERE SALARIO > 2000;
SELECT * FROM TB_EMPREGADOS WHERE SALARIO < 2000;

SET SQL_SAFE_UPDATES = 0;

UPDATE TB_EMPREGADOS SET SALARIO = 1600 WHERE REGISTRO = 4;