CREATE DATABASE DB_LOJAGENERATION;

USE DB_LOJAGENERATION;

CREATE TABLE TB_CATEGORIA (
ID BIGINT(5) AUTO_INCREMENT,
DESCRICAO CHAR(255) NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT(5) AUTO_INCREMENT,
NOME VARCHAR(255) NOT NULL,
PRECO DECIMAL(6,2) NOT NULL, -- O NÚMERO VAI TER 6 NÚMERO ANTES DA VÍRGULA E 2 DEPOIS
QTPRODUTO INT NOT NULL,
CATEGORIA_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY(CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID)
);

INSERT INTO TB_CATEGORIA (DESCRICAO)
VALUES ("PERIFÉRICOS");
INSERT INTO TB_CATEGORIA (DESCRICAO)
VALUES ("SOFTWARE");
INSERT INTO TB_CATEGORIA (DESCRICAO)
VALUES ("ADESIVOS");

SELECT * FROM TB_CATEGORIA;

INSERT INTO TB_PRODUTOS (NOME, PRECO, QTPRODUTO, CATEGORIA_ID)
VALUES ("MOUSE", 20, 4, 1);
INSERT INTO TB_PRODUTOS (NOME, PRECO, QTPRODUTO, CATEGORIA_ID)
VALUES ("MENINAS SUPER PODEROSAS", 5, 10, 3);
INSERT INTO TB_PRODUTOS (NOME, PRECO, QTPRODUTO, CATEGORIA_ID)
VALUES ("TECLADO", 180, 6, 1);


SELECT * FROM TB_PRODUTOS;

SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "M%"; -- VAI MOSTRAR APENAS OS PRODUTOS QUE COMECEM COM A LETRA M

SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%P%"; -- VAI MOSTRAR TUDO O QUE TIVER P NO NOME

SELECT CATEGORIA_ID, NOME, PRECO, QTPRODUTO, DESCRICAO FROM TB_PRODUTOS INNER JOIN TB_CATEGORIA ON
TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIA.ID;

SELECT * FROM TB_PRODUTOS RIGHT JOIN TB_CATEGORIA ON
TB_PRODUTOS.CATEGORIA_ID = TB_CATEGORIA.ID;